In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3],dtype=int32)
# Here we are defining an array [1,2,3]
# datatype of array is also defined as int32 i.e.. it can take 32 bit values
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
# here b is a 
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get Dimension
a.ndim

1

In [ ]:
# Get Shape
# it gives both dimensions and no of elements
b.shape

(2, 3)

In [ ]:
# Get Type
# it gives the data type of array
a.dtype

In [ ]:

# it gives the datatype of each element in the array i.e.. (32/8)=4
a.itemsize

4

In [ ]:
# It gives the size of all elments in array i.e.. 3*4=12
a.nbytes

12

In [ ]:
# size means number of elements in an array
a.size

3

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
# here there are 2 rows and 7 elemnts in each
# here comma seperates two rows

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
a[1, 5]

13

In [ ]:
# 
p=a[0,:]
print(p)

[1 2 3 4 5 6 7]


In [ ]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]
#

array([2, 4, 6])

In [ ]:
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

In [ ]:
# Get specific element (work outside in)
b[0,1,1]

In [ ]:
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

In [ ]:
# Any other number
np.full((2,2), 99)

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

In [ ]:
# The identity matrix
np.identity(5)
# here 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
# here we are repeating [1,2,3] in three rows
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
# we are defining 1st element 100

[100   2   3]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)
# we are merging z with output
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


In [ ]:
a + 2

array([3, 4, 5])

In [ ]:
a - 2

array([-1,  0,  1])

In [ ]:
a / 2

array([0.5, 1. , 1.5])

In [ ]:
b=np.array([1,0,1])
a+b

array([2, 2, 4])

In [ ]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [ ]:
a ** 2

array([1, 4, 9])

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats,axis=1)
# axis=1 means column
# which gives max column

array([3, 6])

In [ ]:
np.sum(stats, axis=0)
# sum of corresponding elements in rows

array([5, 7, 9])

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
# converts into 4 different arrays
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
import numpy as np
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
# convert h1 and h2 into a single array
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])