In [ ]:
import numpy as np

In [ ]:
my_python_list =[1,9,3,6]
print(my_python_list)

[1, 9, 3, 6]


In [ ]:
numpy_array_from_list=np.array(my_python_list)
#here list is changed into array 
numpy_array_from_list

array([1, 9, 3, 6])

In [ ]:
a=np.array([1,9,3,5])
print(a)

[1 9 3 5]


In [ ]:
x=numpy_array_from_list+10
# here 10 is added to each and every number of array i.e.. 1+10=11,9+10=19,3+10=13,6+10=16
print(x)

[11 19 13 16]


In [ ]:
a=np.array([1,2,18,3,6])
# shape of an array says about its dimensions and no_of_objects in it
# as they are 5 elements shape is 5
print(a.shape)
# here datatype indicates whether the data is complex or int or float
# 64 in int64 indicates no_of_bits in an element
print(a.dtype)

(5,)
int64


In [ ]:
b=np.array([5.6,2.4,1.2,0.9])
# shape of an array says about its dimensions and no_of_objects in it
# as they are 4 elements shape is 4
print(b.shape)
# here datatype indicates whether the data is complex or int or float
# 64 in float64 indicates no_of_bits in an element
print(b.dtype)

(4,)
float64


In [ ]:
arr = np.array([[1, 2, 3, 4,19], [5, 6, 7, 8,10]])
# shape of an array says about its dimensions and no_of_objects in it
# here there are 2 dimensions and 5 elements in each  dimension
print(arr.shape)

(2, 5)


In [ ]:
d=np.array([[1, 2, 3, 4, 19], 
            [5, 6, 7, 8, 10]])
print(d)

[[ 1  2  3  4 19]
 [ 5  6  7  8 10]]


In [ ]:
d = np.array([
    [[1, 2, 3],
        [4, 5, 6]],
    [[7, 8, 9],
        [10, 11, 12]]
])
print(d.shape)
# shape of an array says about its dimensions and no_of_objects in it
# here there are two parts in each one there are two dimensions . In each dimension there are 3 elements
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
# here np.zeroes gives a new array in which all elements are 0
#In np.ones((2,2):
# Here 2 is no_of_dimensions 
# here 2 is no_of_elements
print(x)

[[[0 0]
  [0 0]]]


In [ ]:
import numpy as np
y=np.ones((3,4), dtype=np.int64)
#In np.ones((3,4):
# Here 3 is no_of_dimensions 
# here 4 is no_of_elements
#here np.ones gives a new array in which all elements are 1
print(y.shape)	
print(y)

(3, 4)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
#here e is rearranged from 2 dimensions and 3 elements each to 3 dimensions and 2 elements each
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
e.flatten()
# here e= np.array([(1,2,3), (4,5,6)])
# flatten changes e from [[1 2 3],[4 5 6]] to [1,2,3,4,5,6],which means it it changes all dimensions into a single one

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])
#here hstack is used to print the data i.e f and g in one horizontal line without commas
print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [ ]:
# Horizontal  stack
import numpy as np
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])
# here vstack is used to print the data vetically like f in a line and g in next like without commas in between 
print(np.vstack((f, g)))

[[1 2 3]
 [4 5 6]]


In [ ]:
A = np.matrix(np.ones((4,4)))	
# here a matrix of 4*4 order in which all elements are equal	
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.asarray(A)[1]=2
#here A is a matrix of 4 rows and 4 columns in which each element is 1
#here  np.asarray(A)[1]=2 indicates to change 2nd row elements to 2
# if np.asarray(A)[2]=2 indicates to change 3rd row elements to 2
print(A)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.arange(1, 11)
# here 1 is start and 11 is stop(so 11 is not present in the array)
# here are elements from 1 to 10 is arranged in a single array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 14, 4)
# here 1 is start
# here 14 is stop(here the numbers will be included which are less thsn 14)
# here 4 is the increment which means:
# 1 is the start then (1+4=5) is the second element in array
# this continues until the number is less than 14

array([ 1,  5,  9, 13])

In [ ]:
import numpy as np
np.linspace(4.0, 10.0,num=20)
# here 4.0 is start point(first number in sequence)
# here 10.0 is end point(last number in sequence)
# here num=20 is number of samples needs to be generated
# here line space means space is used if there is no decimal number

array([ 4.        ,  4.31578947,  4.63157895,  4.94736842,  5.26315789,
        5.57894737,  5.89473684,  6.21052632,  6.52631579,  6.84210526,
        7.15789474,  7.47368421,  7.78947368,  8.10526316,  8.42105263,
        8.73684211,  9.05263158,  9.36842105,  9.68421053, 10.        ])

In [ ]:
np.linspace(1.0, 5.0, num=5, endpoint=False)
# here 1.0 is start point(first number in sequence)
# here 5.0 is end point(last number in sequence)
# here num=5 is number of samples needs to be generated
# here endpoint = false means endpoint is not included

array([1. , 1.8, 2.6, 3.4, 4.2])

In [ ]:
np.logspace(2.0, 4.0, num=5,endpoint=True)
# here default base is 10
# here log space means considering the values of start point and end point in log base 10 form
# for example 2.0 is start point in the code , 2.0 is written as log 100 base 10
# 4.0 is end point in the code it can be written as log 10000 base 10
# num=5 which means we need to write 5 numbers between the 100 and 10000
# if endpoint is true we can include endpoint in the array
# if endpoint is false endpoint is not included in array
# we can also define the base value and datatype

array([  100.        ,   316.22776602,  1000.        ,  3162.27766017,
       10000.        ])

In [ ]:
x = np.array([10,5], dtype=np.complex128)
# here itemsize is number of bytes an item(here 10 is an item , 5 is an item)
# each and every element in array is considered as an item
# default datatype is int64 in which there are 8 bytes i.e (64/8=8)
# for complex128 there are 16 bytes. so item size is 16 bytes
x.itemsize

16

In [ ]:
import numpy as np
e = np.array([(4,5,6), (7,8,9)])
print(e)
# here ',' slices the function into 2 parts like [4 5 6] in one  [7 8 9] in other one

[[4 5 6]
 [7 8 9]]


In [ ]:
# First row
print('First row:', e[0])
# Here e[0] indicate first row 
# Second row
# e[1] indicate second row
print('Second row:', e[1])

First row: [4 5 6]
Second row: [7 8 9]


In [ ]:
print('First column:', e[:,0])
# Here e[:,0] means 1st column 

First column: [4 7]


In [ ]:
#Second column 1st one value
print(e[:1,1])
# in (e[:1,1]) :1 indicates first element of the column and ,1 indicates Second column

[5 8]


In [ ]:
normal_array = np.random.normal(10, 2, 8)
# here 10 is loc(mean)
# here  2 is scale(standard deviation)
#here 8 is size(no of returns)
print(normal_array)

[ 5.11955145  8.93535362  7.49387709 14.30594402 10.82113473 12.1757518
  5.1053117   7.81931144]


In [ ]:
###Min number in the normal array
print(np.min(normal_array))
### Max number in the normal array 
print(np.max(normal_array))
### Mean of all numbers in the normal array
print(np.mean(normal_array))
### Median  of all numbers in the normal array
print(np.median(normal_array))
### Sd of number in the normal array
print(np.std(normal_array))

5.105311703264474
14.30594401665293
8.972029482135856
8.377332530247532
3.070867203943699


In [ ]:
f = np.array([1,2])
g = np.array([4,5])
# Here multiplication of corresponding elements in f and g is done ,i.e 1*4+2*5=14
np.dot(f, g)


14

In [ ]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
# here matmul means product of two matrices(arrays)
# 1*5+2*7 = 19
np.matmul(h, i)

In [ ]:
# here A needs to be square matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
# inverse of A is caluclated here
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [ ]:
n_array = np.array([[5, 2, 9], [3, 4, 8],[2, 1, 5]])  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
 # Determinent is caluclated here
det = np.linalg.det(n_array)
print("\nDeterminant of given 3*3 matrix:")
print(int(det))

Numpy Matrix is:
[[5 2 9]
 [3 4 8]
 [2 1 5]]

Determinant of given 3*3 matrix:
17


In [ ]:
m = np.array([[1,1,1],[1,0,2],[1,9,2]])
# Here rank of matrix is caluclated using np.linalg.matrix_rank()
np.linalg.matrix_rank(m)

3

In [ ]:
matrix = np.array([
[0,2,1],
[1,0,2],
[1,2,0]
])
# here eigen values and vectors are caluclated by using np.linalg.eig()
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues) 
print(eigenvectors)

[-1.  3. -2.]
[[-0.90453403  0.57735027  0.48507125]
 [ 0.30151134  0.57735027 -0.72760688]
 [ 0.30151134  0.57735027  0.48507125]]


In [ ]:
g = np.matrix('[6, 2, 8; 3, 4, 6; 1, 7, 10]')        
# Here diagonal of a matrix is caluclated using g.diagonal()
diag = g.diagonal()
print(diag)

[[ 6  4 10]]


In [ ]:
f = np.matrix('[4, 1; 12, 3]')              
# Here transpose of a matrix is caluclated using f.transpose()
trans = f.transpose()   
print(trans)

[[ 4 12]
 [ 1  3]]


In [ ]:
a = np.matrix('[4, 2; 1, 6]')           
# Here trace of a matrix is caluclated using a.trace()
Trace_of_matrix = a.trace()   
print(Trace_of_matrix)

[[10]]
